% Script generated by Brainstorm (21-Jun-2023)

% Input files
sFiles = [];
%SubjectNames = {'sub-0003', ...
    %'sub-0004', 'sub-0006', 'sub-0007'};

SubjectNames = {'sub-0002'};
% Start a new report
bst_report('Start', sFiles);

% Process: Segment MRI with CAT12
num_subs=16;
for i=1:num_subs
    sFiles = bst_process('CallProcess', 'process_segment_cat12', sFiles, [], ...
        'subjectname', SubjectNames{i}, ...
        'nvertices',   15000, ...
        'tpmnii',      {'', 'Nifti1'}, ...
        'sphreg',      1, ...
        'vol',         1, ...
        'extramaps',   1, ... %%make sure this is 1!!
        'cerebellum',  0);
    
    % Save and display report
    ReportFile = bst_report('Save', sFiles);
    bst_report('Open', ReportFile);
    bst_report('Export', ReportFile, '/export02/data/vikramn/brainstorm3/reports/');
    % bst_report('Email', ReportFile, username, to, subject, isFullReport);
    
    % Delete temporary files
    % gui_brainstorm('EmptyTempFolder');
end

